# Generated by Django 4.1.5 on 2023-11-04 06:55

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('managertest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='magazine',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
