# Generated by Django 4.1.7 on 2024-09-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("soft_delete", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="softdelete",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
