# Generated by Django 4.1.7 on 2024-09-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("soft_delete", "0002_alter_softdelete_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="softdelete",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="softdelete",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", False)),
                fields=("name",),
                name="unique_name_partial_index",
            ),
        ),
    ]
