# Generated by Django 4.1.7 on 2025-01-12 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fluid", "0002_dynamictabledata"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivedDynamicTableData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archived_data",
                        to="fluid.tablemetadata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Archived Dynamic Table Data",
                "verbose_name_plural": "Archived Dynamic Table Data",
            },
        ),
        migrations.AddIndex(
            model_name="archiveddynamictabledata",
            index=models.Index(
                fields=["created_at"], name="fluid_archi_created_ca9f56_idx"
            ),
        ),
    ]
