# Generated by Django 4.1.5 on 2023-04-23 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.option'),
        ),
    ]
