# Generated by Django 4.1.5 on 2023-04-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
